### ISSUE TITLE
现在还可用吗？

### ISSUE THREAD

**Issue by 314538494** [kenyon-wong/anki-sync-server-docker#2]

**Comment by kenyon-wong** [comment]
可以啊，镜像没有托管到 docker hub ，只能手动编译或者使用 GitHub actions 进行编译

**Comment by 314538494** [comment]
那就是在群晖的docker还弄不了，对吧？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月22日(周六) 晚上9:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kenyon-wong/anki-sync-server-docker] 现在还可用吗？ (Issue #2)




 
可以啊，镜像没有托管到 docker hub ，只能手动编译或者使用 GitHub actions 进行编译

**Comment by 314538494** [comment]
感谢回复我也是刚接触docker所以你说的编译什么的听不太懂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月22日(周六) 晚上9:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kenyon-wong/anki-sync-server-docker] 现在还可用吗？ (Issue #2)




 
可以啊，镜像没有托管到 docker hub ，只能手动编译或者使用 GitHub actions 进行编译
